#!/bin/sh

# Update installed brew packages for good measure
brew update && brew upgrade

set -e

cd "$(dirname $0)"/..
export DOTFILES_ROOT=`pwd`

# find the installers and run them iteratively
find . -name install.sh | sort | while read installer ; do sh -c "${installer}" ; done
