#!/bin/sh

# chruby
source '/usr/local/share/chruby/chruby.sh'
source '/usr/local/share/chruby/auto.sh'
chruby 2.1.2

set -e

cd "$(dirname $0)"/..
export DOTFILES_ROOT=`pwd`

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
